### ISSUE TITLE
Missing Data

### ISSUE THREAD

**Issue by somdats** [ChirikjianLab/LSG-CPD#2]
@bmlklwx . @hongtaowu67 
I would like to run your source code, however, The data is missing. WOuld it be possible to share the data used in your experiments?

Thanks

**Comment by bmlklwx** [comment]
The demo data is in [here](https://drive.google.com/file/d/1_7v1L1O_YtVbIvRzMQKClIz3TUi5mlbE/view?usp=sharing).
Complete outlier and noise data is [here](https://drive.google.com/file/d/1_7v1L1O_YtVbIvRzMQKClIz3TUi5mlbE/view?usp=sharing)
The original data can be accessed through the [official repo](http://graphics.stanford.edu/data/3Dscanrep/).

**Comment by bmlklwx** [comment]
> 

The demo data is in [here](https://drive.google.com/file/d/1_7v1L1O_YtVbIvRzMQKClIz3TUi5mlbE/view?usp=sharing).
Complete outlier and noise data is [here](https://drive.google.com/file/d/1_7v1L1O_YtVbIvRzMQKClIz3TUi5mlbE/view?usp=sharing)
The original data can be accessed through the [official repo](http://graphics.stanford.edu/data/3Dscanrep/).

**Comment by somdats** [comment]
> > 
> 
> hi @somdats, thx for your interest. The demo data is in [here](https://drive.google.com/file/d/1_7v1L1O_YtVbIvRzMQKClIz3TUi5mlbE/view?usp=sharing). Complete outlier and noise data is [here](https://drive.google.com/file/d/1_7v1L1O_YtVbIvRzMQKClIz3TUi5mlbE/view?usp=sharing) The original data can be accessed through the [official repo](http://graphics.stanford.edu/data/3Dscanrep/).

Thanks a lot
